### PR TITLE
Add -std=c++11 to DRV_CFLAGS in rebar.config

### PR DESCRIPTION
**Pull request by dcheckoway**
We needed this to get the NIF to compile.

### CODE REVIEW

**Comment by tuncer** [comment]
Duplicate, see #6. This is included since 1.3.0. Also, if you have a minute, I could use your feedback in #10.

**Comment by tuncer** [comment]
Thanks, but this is a duplicate, see #6. The same change landed in 1.3.0. Also, if you have a minute, I could use your feedback in #10.

**Comment by dcheckoway** [comment]
@tuncer this is not a duplicate.  This was a separate change that is _also_ needed.

**Comment by tuncer** [comment]
Hmm, it works for me with gcc and clang. re2_nif.cpp doesn't use C++11, and it's just upstream re2 that does, plus I didn't have any link-time errors with either clang or gcc. What error are you seeing?

**Comment by tuncer** [comment]
It seems re2.h requires C++11 as well now.

**Comment by tuncer** [comment]
This is caused by changes after the tag 2016-03-01, namely `eb00dfd Use std::call_once for lazy initialization`.

**Comment by tuncer** [comment]
Sorry, you're right, and this seems to have happened just recently upstream. Good catch!

Thanks for tha patch. I've committed it in the rebar3 branch and merged that to master after doing some minor changes. I couldn't merge this as is due to the rebar3 support modifications, which replaced rebar.config with rebar.config.script.

**Comment by tuncer** [comment]
Does master work for you?

**Comment by tuncer** [comment]
I'll delay cutting a release until I get confirmation from you.

**Comment by dcheckoway** [comment]
@tuncer, yup, 7516ad193ab0ad39b69a8a4289a1780a82b73593 works for us.

**Comment by tuncer** [comment]
Included in 1.4.0.

**Pull request closed without merging**
